### PR TITLE
63 add database logging functionality

### PR DESCRIPTION
**Pull request by LukasFehring**

### CODE REVIEW

**Review by tornede — CHANGES_REQUESTED** [review]
- [ ] There are warnings in the mysql view of all tables, which should be removed/solved.
- [x] The LogTables are missing the timestamp column as noted in the issue
- [ ] The order of the columns should be:
    1. ID
    2. experiment_id
    3. timestamp
    4. other columns in order of the config file

**Comment by LukasFehring** [comment]
> * [ ]  There are warnings in the mysql view of all tables, which should be removed/solved.

These warnings seem to get caused by the database connection to a 'modern' database. Therefore the comment should be moved to #61 .

**Review by tornede — CHANGES_REQUESTED** [review]
- [x] Update documentation

**Comment by alexandertornede** [comment]
So I tried using the new functionality in one of the examples and I have two problems with running the examples in the first place: 
1. The cell writing the example config fails, if the config folder does not already exists. Thus, it should be created, if it does not exist yet. 
2. When running the cell executing the PyExperimenter, I get the following error: 
`AttributeError: Can't get attribute 'run_ml' on <module '__main__' (built-in)>`

**Comment by LukasFehring** [comment]
> 1. The cell writing the example config fails, if the config folder does not already exists. Thus, it should be created, if it does not exist yet.
This is updated

> 2. When running the cell executing the PyExperimenter, I get the following error:
>    `AttributeError: Can't get attribute 'run_ml' on <module '__main__' (built-in)>`
I can not reproduce this error.

**Comment by LukasFehring** [comment]
I also added documentation and an example notebook. Note that this branch is checked out before #87  is merged into develop. Therefore, we must manually add string identifiers when writing a string into a log-table. This should be fixed by closing the aforementioned issue

**Comment by alexandertornede** [comment]
@LukasFehring 

I retried running the examples and it still fails for me. Steps to reproduce on a MAC with Mac OS Monterey (12.6): 

1. Install the environment. 
2. Open the project in Pycharm (2022.2.4) and run any of the example notebooks in Pycharm from top to bottom. The cell with `experimenter.execute...` gives the following error: 
`Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/Users/.../anaconda3/envs/pyexperimenter/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/.../anaconda3/envs/pyexperimenter/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/.../anaconda3/envs/pyexperimenter/lib/python3.9/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/Users/.../anaconda3/envs/pyexperimenter/lib/python3.9/multiprocessing/queues.py", line 367, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'run_ml' on <module '__main__' (built-in)>`

I shortened some of the paths in the above error.

**Comment by LukasFehring** [comment]
T

> @LukasFehring
> 
> I retried running the examples and it still fails for me. Steps to reproduce on a MAC with Mac OS Monterey (12.6):
> 
> 1. Install the environment.
> 2. Open the project in Pycharm (2022.2.4) and run any of the example notebooks in Pycharm from top to bottom. The cell with `experimenter.execute...` gives the following error:
>    `Process SpawnPoolWorker-2: Traceback (most recent call last):   File "/Users/.../anaconda3/envs/pyexperimenter/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap self.run()   File "/Users/.../anaconda3/envs/pyexperimenter/lib/python3.9/multiprocessing/process.py", line 108, in run self._target(*self._args, **self._kwargs)   File "/Users/.../anaconda3/envs/pyexperimenter/lib/python3.9/multiprocessing/pool.py", line 114, in worker task = get()   File "/Users/.../anaconda3/envs/pyexperimenter/lib/python3.9/multiprocessing/queues.py", line 367, in get return _ForkingPickler.loads(res) AttributeError: Can't get attribute 'run_ml' on <module '__main__' (built-in)>`
> 
> I shortened some of the paths in the above error.
> 
> Edit: I also get the same error when running it outside of Pycharm.

This prompted us to use joblib instead of pytons own multiprocessing. The issue #102 deals with this. It is finished but needs to merged on dev.

**Comment by alexandertornede** [comment]
With the fixes from the other branch and the adapted usage and example documentation, it looks good to me now.

**Review by alexandertornede — APPROVED** [review]

**Review by tornede — APPROVED** [review]
LGTM

**Pull request merged**
